-- AEC registration schema
-- Run this script in Supabase SQL Editor

-- Optional: enable extension for generating UUIDs if needed later
create extension if not exists pgcrypto;

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  wilaya text not null check (wilaya in ('Alger', 'Oran', 'Ouargla', 'Constantine')),
  team_name text not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  num_members integer not null check (num_members in (3, 4)),
  different_universities boolean,
  can_attend_physically boolean,
  participated_before boolean,
  participation_experience text,
  hands_on_experience boolean,
  hands_on_details text,
  motivation text,
  heard_about text,
  anything_to_add text,
  created_at timestamptz not null default now()
);

alter table public.teams
  add column if not exists status text not null default 'pending';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'teams_status_check'
  ) then
    alter table public.teams
      add constraint teams_status_check
      check (status in ('pending', 'accepted', 'rejected'));
  end if;
end
$$;

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  is_leader boolean not null default false,
  full_name text not null,
  email text not null,
  phone text not null,
  discord text not null,
  linkedin text not null,
  university text not null,
  field_of_study text not null,
  year_of_study text not null check (year_of_study in ('1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year', '+6th Year')),
  software_tools text[] not null default '{}',
  created_at timestamptz not null default now(),
  constraint members_email_team_unique unique (team_id, email)
);

create index if not exists idx_members_team_id on public.members(team_id);
create index if not exists idx_members_email on public.members(email);

-- Recommended RLS setup for public insert-only registration flow
alter table public.teams enable row level security;
alter table public.members enable row level security;

-- Allow anonymous users to insert registration data
drop policy if exists "allow_anon_insert_teams" on public.teams;
create policy "allow_anon_insert_teams"
on public.teams
for insert
to anon
with check (true);

drop policy if exists "allow_anon_select_teams" on public.teams;
create policy "allow_anon_select_teams"
on public.teams
for select
to anon
using (true);

drop policy if exists "allow_anon_update_team_status" on public.teams;
create policy "allow_anon_update_team_status"
on public.teams
for update
to anon
using (true)
with check (status in ('pending', 'accepted', 'rejected'));

drop policy if exists "allow_anon_insert_members" on public.members;
create policy "allow_anon_insert_members"
on public.members
for insert
to anon
with check (true);

drop policy if exists "allow_anon_select_members" on public.members;
create policy "allow_anon_select_members"
on public.members
for select
to anon
using (true);

-- Optionally allow service role/full backend to read all
drop policy if exists "allow_service_role_select_teams" on public.teams;
create policy "allow_service_role_select_teams"
on public.teams
for select
to service_role
using (true);

drop policy if exists "allow_service_role_select_members" on public.members;
create policy "allow_service_role_select_members"
on public.members
for select
to service_role
using (true);

create or replace function public.update_team_status(p_team_id bigint, p_status text)
returns public.teams
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_team public.teams;
begin
  if p_status not in ('pending', 'accepted', 'rejected') then
    raise exception 'Invalid team status: %', p_status;
  end if;

  update public.teams
  set status = p_status
  where id = p_team_id
  returning * into updated_team;

  if not found then
    raise exception 'Team % not found', p_team_id;
  end if;

  return updated_team;
end;
$$;

revoke all on function public.update_team_status(bigint, text) from public;
grant execute on function public.update_team_status(bigint, text) to anon;

create or replace function public.delete_teams(p_team_ids bigint[])
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.teams
  where id = any(p_team_ids);

  get diagnostics deleted_count = row_count;

  return deleted_count;
end;
$$;

revoke all on function public.delete_teams(bigint[]) from public;
grant execute on function public.delete_teams(bigint[]) to anon;
